using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerInput : MonoBehaviour
{
    public Vector2 inputDirection;
    public bool jumpButton;
    MovementScript movement;
    // Start is called before the first frame update
    void Start()
    {
        movement = GetComponent<MovementScript>();
    }

    // Update is called once per frame
    void Update()
    {
        inputDirection = new Vector2(Input.GetAxisRaw("Horizontal"), Input.GetAxisRaw("Vertical"));
        jumpButton = Input.GetButtonDown("Jump");

        movement.direction = inputDirection;
        movement.jump = jumpButton;
    }
}
